<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
# Imports
import numpy as np

In [2]:
# Create data
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [0,1,0],
            [1,0,0],
            [1,1,1],
            [0,0,0]])
y = np.array([[0],
             [1],
             [1],
             [1],
             [1],
             [0],
             [0]])

In [3]:
# Define NN class
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # Initialize Weights
        # First layer - 3x4 Matrix Array 
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        
        # Hidden Layer to output 4x1 Matrix Array
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    # define Sigmoid function
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    # define Sigmoid prime function
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    # define feed forward function
    def feed_forward(self, X):
        """
        Calculate NN inference using feed forward.
        """
        
        # Weighted sum of inputs -> hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    # define backpropagation function
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        # Find error in output:
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # How much z2 error can be explained by first layer of weights
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights
        self.weights1 += X.T.dot(self.z2_delta)
        
        # Adjustment to second set of weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    # Define train function
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [17]:
# Instantiate model
nn = NeuralNetwork()

# Make prediction using only feed_forward to check function
output = nn.feed_forward(X[0])
print(output)

[0.70004847]


In [19]:
# Test train function
nn.train(X,y)

In [23]:
nn = NeuralNetwork()

# Train with iterations
for i in range(5000):
    if (i+1 in [1,2,3,4,5]):
        print('____' + f'EPOCH {i+1}' + '____')
       # print('Input: \n', y)
       # print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    if (i+1 == 5000):
        print('____' + f'EPOCH {i+1}' + '____')
        print('Input: \n', y)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

____EPOCH 1____
Predicted Output: 
 [[0.87799136]
 [0.90749849]
 [0.91038299]
 [0.8643266 ]
 [0.8701918 ]
 [0.92651816]
 [0.81080396]]
Loss: 
 0.3340789958169598
____EPOCH 2____
Predicted Output: 
 [[0.7519766 ]
 [0.78576055]
 [0.78718587]
 [0.7452683 ]
 [0.74763444]
 [0.80908974]
 [0.69792848]]
Loss: 
 0.27528059840942826
____EPOCH 3____
Predicted Output: 
 [[0.64197882]
 [0.66863758]
 [0.66660251]
 [0.64446802]
 [0.64161856]
 [0.68517422]
 [0.61080641]]
Loss: 
 0.24721145560832508
____EPOCH 4____
Predicted Output: 
 [[0.59154934]
 [0.61305343]
 [0.60893232]
 [0.59890681]
 [0.59314463]
 [0.62411747]
 [0.57250836]]
Loss: 
 0.24232681195758146
____EPOCH 5____
Predicted Output: 
 [[0.57634276]
 [0.59651629]
 [0.5914965 ]
 [0.58580769]
 [0.57879154]
 [0.60573387]
 [0.56121878]]
Loss: 
 0.24181386642226568
____EPOCH 5000____
Input: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[2.05109665e-05]
 [9.91992013e-01]
 [9.91932889e

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [4]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [5]:
# input image dimensions
img_rows, img_cols = 28, 28

In [6]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [7]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [8]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [9]:
y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [10]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [17]:
##### Your Code Here #####
# Define NN class
class MnistNet:
    def __init__(self):
        # Set up Architecture
        self.inputs = 784
        self.hiddenNodes = 2
        self.outputNodes = 1
        
        # Initialize Weights
        # First layer - 784x28 Matrix Array 
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        
        # Hidden Layer to output 28x1 Matrix Array
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    # define Sigmoid function
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    # define Sigmoid prime function
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    # define feed forward function
    def feed_forward(self, X):
        """
        Calculate NN inference using feed forward.
        """
        
        # Weighted sum of inputs -> hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    # define backpropagation function
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        # Find error in output:
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # How much z2 error can be explained by first layer of weights
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights
        self.weights1 += X.T.dot(self.z2_delta)
        
        # Adjustment to second set of weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    # Define train function
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)


In [12]:
# Instantiate model
nn = MnistNet()

# Make prediction using only feed_forward to check function
output = nn.feed_forward(x_train[100])
print(output)

[0.69267684]


In [18]:
nn.backward(x_train, y_train, output)

ValueError: shapes (60000,) and (1,2) not aligned: 60000 (dim 0) != 1 (dim 0)

In [13]:
# Test train function
nn.train(x_train, y_train)

KeyboardInterrupt: 

In [ ]:
nn = NeuralNetwork()

# Train with iterations
for i in range(100):
    if (i+1 in [1,2,3,4,5]):
        print('____' + f'EPOCH {i+1}' + '____')
       # print('Input: \n', y)
       # print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    if (i+1 == 5000):
        print('____' + f'EPOCH {i+1}' + '____')
        print('Input: \n', y)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?